---
title: "Covid Data and Restrictions - Plotting data"
output: github_document
---
```{r setup, echo=FALSE, message=FALSE, warning=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```


Load required packages
```{r}
if (!require(pacman)) install.packages('pacman')
library(pacman)
p_load(tidyverse,ggpubr, map_data,ggrepel,ggtext,scales,viridis,ggthemes)
options(scipen=999)
options(warn=-1)
```

Import data frames saved from Extraction.RMD
```{r}
df <- readRDS("OxOw_Extraction_large.rds")
df_small <- readRDS("OxOw_Extraction_small.rds")
```

## Plot Total Restrictions on World MAP
```{r}
#select date to run analysis 
date_input <- "2022-05-20"

#filter data frames 
df_world <- df %>% filter(date == date_input)
world_map <- map_data("world")
world_map <- world_map  %>% select(-c(order,subregion))

#change region to location for consistency
names(world_map)[4] <- "location"

#change USA to United states for consistency
world_map$location <- gsub("USA", "United States", world_map$location)

#merge dataframes based on country location
world <- full_join(world_map,df_world, by = 'location') %>% 
#select only specific columns
select(location,total_restrictions, group, long, lat)

# summarise data to reduce to one country per row
world_lab_data <- world %>%
  group_by(location) %>%
  summarise(long = mean(long), lat = mean(lat), group = max(group), 
            total_restrictions = max(total_restrictions))

#remove antarctica from dataset
world_lab_data <- world_lab_data %>% filter(location != "Antarctica")
world <- world %>% filter(location != "Antarctica" )

#plot map using ggplot 
ggplot(world, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = total_restrictions), colour = 'white') +
  scale_fill_viridis_c(option = "C", direction = -1) +
  labs(fill = "Total restrictions") +
  labs(title = "Covid Restrictions World Map",
            subtitle = paste0("as of ", date_input))+
  geom_text(data = world_lab_data, x = 10, 
            y = 70, label = "Sweden",stat = "unique", size =4, colour = 'darkgreen') +
  geom_text(data = world_lab_data, x = 85, 
            y = 5, label = "India",stat = "unique", size = 4.5, colour = 'red') +
  geom_text_repel(data = world_lab_data, aes(label = location), max.overlaps = 2,
            size=3.5, min.segment.length = 2, colour = 'black') +
  theme_map() +
  theme(    axis.title=element_blank(),
            axis.text=element_blank(),
            axis.ticks=element_blank(),
            plot.title = element_text(hjust = 0.5, size = 16, family="serif"),
            plot.subtitle = element_text(hjust = 0.5, size = 12),
            legend.text=element_text(size=12,family="serif"),
            legend.title=element_text(size=13,family="serif"),
            legend.position="right",
            legend.direction = "vertical")
```


#Scatter plot country comparison
```{r}
#function to filter by date
df_filter_date <- function(dt){
    df <- df_small %>%
      filter(date == dt) %>% 
      filter(!is.na(continent)) %>% 
      select(continent, location, date, cum_c2_workplace_closing,cum_c6_stay_at_home_requirements,
             cum_c7_restrictions_on_internal_movement,cum_h6_facial_coverings,
             total_restrictions, total_deaths_per_million) %>%
      drop_na()
}
#function to filter by continent and date
df_continent_date <- function(ct,dt){
    df <- df_small %>%
      filter(date == dt) %>% 
      filter(!is.na(continent)) %>% 
      select(continent, location, date, cum_c2_workplace_closing,cum_c6_stay_at_home_requirements,
             cum_c7_restrictions_on_internal_movement,cum_h6_facial_coverings,
             total_restrictions,total_deaths_per_million) %>%
      filter(continent == ct) %>% 
      drop_na()
}

#function to plot scatter plot 
country_scatter <- function(df_input, x_metric, title) {
  min_x <- df_input %>% select(x_metric) %>% min(na.rm = T)
  max_y <- df_input %>% select('total_deaths_per_million') %>% max(na.rm = T)
  if (title == 'yes') {Switch = T}
  else {Switch = F}

  date <- df_input %>% select(date) %>% filter(row_number()==1) %>% pull()
  plot <- df_input %>% 
ggplot(aes_string(x = x_metric, y = "total_deaths_per_million", label = "location")) +
        geom_point(data = df_input, aes(color = continent)) +
        geom_smooth(method = lm, se = F, colour = 'grey') +
        facet_wrap(~continent) +
        scale_size_continuous(range = c(2,10)) +
        scale_color_viridis(discrete = TRUE, option = 'C') +
        geom_text_repel(max.overlaps = 10, size = 3) +
        annotate("text", label= paste0("R = ", round(with(df_input,
                cor.test(total_deaths_per_million, get(x_metric), method = "pearson"))$estimate, 2),", p = ", 
                round(with(df_input,cor.test(total_deaths_per_million, get(x_metric), method = "pearson"))$p.value, 3),
                ", n = ", nrow(df_input)),x = min_x *1.5, y = max_y, color = "red", size = 3) +
        labs(color = "Continent") +
        ylab("Total deaths per million") +
        xlab(x_metric) +
        {if(Switch)ggtitle(paste0("Total deaths per million vs ", x_metric, " as of ", date))} +
        guides(color = guide_legend(override.aes = list(size = 7))) +
        theme_minimal()+
        theme(axis.title = element_text(size = 14, family="serif"),
              axis.text = element_text(size = 12, family="serif"),
              legend.title = element_text(size = 13,family="serif"),
              legend.text = element_text(size = 10,family="serif"),
              plot.title = element_text(size = 14, family="serif"),
              plot.title.position = 'plot'
              )
  return(plot)
}

#plot scatter plots 
country_scatter(df_filter_date(date_input),"total_restrictions",'yes')
country_scatter(df_filter_date(date_input),"cum_c2_workplace_closing",'yes')
country_scatter(df_filter_date(date_input),"cum_c6_stay_at_home_requirements",'yes')
country_scatter(df_filter_date(date_input),"cum_c7_restrictions_on_internal_movement",'yes')
country_scatter(df_filter_date(date_input),"cum_h6_facial_coverings",'yes')
#select continent and date

ggarrange(country_scatter(df_continent_date("Asia",date_input),"total_restrictions",'no'),
          country_scatter(df_continent_date("North America",date_input),"total_restrictions",'no'),
          country_scatter(df_continent_date("Europe",date_input),"total_restrictions",'no'),
          country_scatter(df_continent_date("Africa",date_input),"total_restrictions",'no'),
          country_scatter(df_continent_date("South America",date_input),"total_restrictions",'no'),
          country_scatter(df_continent_date("Oceania",date_input),"total_restrictions",'no'),
          legend = "none"
          )

europe_lally <- df_small %>% filter(date == "2020-12-30" & continent == 'Europe' & !location %in% c("Malta","Liechtenstein","Monaco","San Marino","Belarus","Andorra","Ukraine","Moldova"))


country_scatter(europe_lally,"max_stringency",'yes')
country_scatter(europe_lally,"total_restrictions",'yes')




```


### Cleanup workspace
```{r}
#cleanup workspace
rm(list=setdiff(ls(), c("df","df_small","world","world_lab_data","date_input")))
```
