---
title: "Covid Data and Restrictions - Regression Models - World"
output: github_document
always_allow_html: yes
---
```{r setup, echo=FALSE, message=FALSE, warning=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
if (!require(pacman)) install.packages('pacman')
library(pacman)
p_load(tidyverse,ggpubr,ggrepel,ggtext,scales,viridis,ggthemes,psych,kableExtra,corrr,car,ggiraphExtra,olsrr)
options(scipen=999)
options(warn=-1)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_world_20211230 <- readRDS("OxOw_Extraction_world_20211230_large.rds")
```


```{r,echo=FALSE, message=FALSE, warning=FALSE}
cor_variables <- c("location","iso_code","date","continent","total_deaths_per_million","people_fully_vaccinated_per_hundred","population_density","median_age","gdp_per_capita","extreme_poverty","cardiovasc_death_rate","diabetes_prevalence","life_expectancy","human_development_index","latitude","sub_stringency","sub_stringency_cubed","first_death_date","date_first_death_days","stringency","obesity_prevalence","lockdowns","lockdowns_cubed")

df_world_20211230 <- df_world_20211230 %>% select(cor_variables)
#replace -inf values with NA
df_world_20211230[sapply(df_world_20211230, is.infinite)] <- NA

corr_table <- function(df){
  date <- df$date[1]
  tble <- df[,unlist(lapply(df, is.numeric))] %>% correlate() %>% focus(total_deaths_per_million) %>% 
  rename(Variable = term) %>% arrange(total_deaths_per_million) %>%  
  kbl(caption = paste0("Correlations - World - Total deaths per million - ",date)) %>% 
  kable_classic(full_width = F)
  
  return(tble)
}

corr_plot <- function (df){
  date <- df$date[1]
  plot <- df[,unlist(lapply(df, is.numeric))] %>% correlate() %>% focus(total_deaths_per_million) %>% 
  mutate(term = factor(term, levels = term[order(total_deaths_per_million)])) %>%
  ggplot(aes(x = term, y = total_deaths_per_million)) +
    geom_bar(stat = "identity", fill = 'purple') +
    ylab("Total deaths per million (corr)") +
    xlab("") +
    ylim(c(-1,1)) +
    ggtitle(paste0("Correlation - World - ",date)) +
    theme_classic2() +
    theme(axis.text.x=element_text(angle=75,hjust=1,vjust=1))
  
  return(plot)
  
}

corr_matrix <- function(df){
  date <- df$date[1]
  corPlot(df[,unlist(lapply(df, is.numeric))],
        min.length = 20,
        scale = FALSE,
        diag = FALSE,
        upper = FALSE,
        alpha = 0.20,
        stars = TRUE,
        cex = 0.5,
        cex.axis = 0.55,
        xlas = 2,
        main = paste0("Correlations - World -  ",date),
        )
  
}
reg_print <- function(model){
  p <- ols_regress(model)
  tib <- capture.output(p, file = NULL, append = FALSE) %>% 
  as_tibble() %>% 
    kbl() %>% 
  kable_classic()

  return(tib)
  
}

vif_print <- function(model){
  
  p <- ols_coll_diag(model)

  out <- p$vif_t %>% select(-Tolerance) %>% arrange(desc(VIF)) %>% 
    kbl() %>% 
  kable_classic()

  return(out)
}



mlr_print <- function(model){
  capture.output(summary(model), file = NULL, append = FALSE) %>% 
  as.tibble() %>% 
  rename(regression = value) %>% 
  kbl() %>% 
  kable_classic()
}

mlr_vif <- function(model){
  vif_values <- vif(model) %>% sort(decreasing=FALSE, na.last=NA)
  barplot(vif_values, main = "VIF Values", col = "steelblue", horiz=F, las=2,cex.names=.6)
  abline(h = 10, lwd = 2, lty = 2)}


create_model_full <- function(df){
  
  model <- lm(formula = total_deaths_per_million ~ median_age + people_fully_vaccinated_per_hundred + population_density + gdp_per_capita + 
                          extreme_poverty + cardiovasc_death_rate + diabetes_prevalence + life_expectancy + human_development_index + latitude + 
                          sub_stringency + date_first_death_days + obesity_prevalence, data = df)
  return (model)
}

create_model_full_2 <- function(df){
  
  model <- lm(formula = total_deaths_per_million ~ median_age + people_fully_vaccinated_per_hundred + population_density + gdp_per_capita + 
                          extreme_poverty + cardiovasc_death_rate + diabetes_prevalence + latitude + 
                          sub_stringency + date_first_death_days + obesity_prevalence, data = df)
  return (model)
}

create_model_full_3 <- function(df){
  
  model <- lm(formula = total_deaths_per_million ~ median_age + people_fully_vaccinated_per_hundred + population_density + gdp_per_capita + 
                          extreme_poverty + cardiovasc_death_rate + diabetes_prevalence + 
                          sub_stringency + date_first_death_days + obesity_prevalence, data = df)
  return (model)
}

create_model_full_4 <- function(df){
  
  model <- lm(formula = total_deaths_per_million ~ median_age + gdp_per_capita + 
                obesity_prevalence, data = df)
  return (model)
}

create_model_stringency <- function(df){
  model <-  lm(formula = total_deaths_per_million ~ median_age + stringency + 
                people_fully_vaccinated_per_hundred,data = df)
  return(model)
} 

create_model_sub_stringency <- function(df){
  model <-  lm(formula = total_deaths_per_million ~ median_age + sub_stringency + 
                people_fully_vaccinated_per_hundred,data = df)
  return(model)
} 

create_model_sub_stringency_cubed <- function(df){
  model <-  lm(formula = total_deaths_per_million ~ median_age + sub_stringency_cubed + 
                people_fully_vaccinated_per_hundred,data = df)
  return(model)
} 

create_model_lockdowns <- function(df){
  model <-  lm(formula = total_deaths_per_million ~ median_age + lockdowns + 
                people_fully_vaccinated_per_hundred,data = df)
  return(model)
} 

create_model_lockdowns_cubed <- function(df){
  model <-  lm(formula = total_deaths_per_million ~ median_age + lockdowns_cubed + 
                people_fully_vaccinated_per_hundred,data = df)
  return(model)
} 


```

```{r}
#function to plot scatter plot 
country_scatter <- function(df_input, y_metric, y_label, x_metric, x_label, title,  equation = "no", facet = 'no') {
  if(df_input %>% select(x_metric) %>% min(na.rm = T) >=1){
    min_x <- df_input %>% select(x_metric) %>% min(na.rm = T)
  }
  else{
    min_x <- df_input %>% select(x_metric) %>% min(na.rm = T)
  }
  
  max_x <- df_input %>% select(x_metric) %>% max(na.rm = T)
  max_y <- df_input %>% select(y_metric) %>% max(na.rm = T)
  if (title == 'yes') {tit = T}
  else {tit = F}
  
  if (equation == 'ann') {ann = T}
  else {ann = F}
  
  if (facet == 'fac') {fc = T}
  else {fc = F}

  date <- df_input %>% select(date) %>% filter(row_number()==1) %>% pull()
  plot <- df_input %>% 
ggplot(aes_string(x = x_metric, y = y_metric, label = "location")) +
        geom_point(data = df_input, aes(color = continent)) +
        geom_smooth(method = lm, se = F, colour = 'grey') +
        {if(fc)facet_wrap(~continent)} +
        scale_size_continuous(range = c(2,10)) +
        scale_color_viridis(discrete = TRUE, option = 'C') +
        geom_text_repel(max.overlaps = 10, size = 3) +
        {if(ann)annotate("text", label= paste0("R = ", round(with(df_input,
                cor.test(total_deaths_per_million, get(x_metric), method = "pearson"))$estimate, 2),", p = ", 
                round(with(df_input,cor.test(total_deaths_per_million, get(x_metric), method = "pearson"))$p.value, 3),
                ", n = ", nrow(df_input)),x = min_x + (0.10 * (max_x - min_x)), y = max_y, color = "red", size = 3)} +
        labs(color = "Continent") +
        ylab(y_label) +
        xlab(x_label) +
        {if(tit)ggtitle(paste0(y_label, " vs ", x_metric, " as of ", date))} +
        guides(color = guide_legend(override.aes = list(size = 7))) +
        theme_minimal()+
        theme(axis.title = element_text(size = 14, family="serif"),
              axis.text = element_text(size = 12, family="serif"),
              legend.title = element_text(size = 13,family="serif"),
              legend.text = element_text(size = 10,family="serif"),
              legend.position="none",
              plot.title = element_text(size = 14, family="serif"),
              plot.title.position = 'plot'
              )
  return(plot)
}

```


```{r}
#map print function
country_map <- function(df,dt,fill_var,title,include_title,leg_label){
  
  if (include_title == 'yes') {Switch = T}
  else if((include_title == 'no')) {Switch = F}
  
  df_world <- df %>% filter(date == dt)

  map_data <- map_data("world") %>% 
    select(-c(order,subregion)) %>% 
    rename(location = region)
  
  map_data$location <- gsub("Czech Republic","Czechia",map_data$location)
  map_data$location <- gsub("USA", "United States", map_data$location)
  map_data$location <- gsub("UK", "United Kingdom", map_data$location)
  
  
  #merge dataframes based on country location
  map_df <- full_join(map_data,df_world, by = 'location') %>% 
  #select only specific columns
  select(location,sub_stringency,sub_stringency_cubed, total_deaths_per_million,
         stringency,lockdowns, lockdowns_cubed, group, long, lat)
  
  #summarise data to reduce to one country per row
  map_lab_data <- map_df %>%
  group_by(location) %>%
  summarise(long = mean(long), lat = mean(lat), group = max(group))

  map_lab_data <- map_lab_data %>% filter(!grepl('Island|Antarctic|South|North', location))

  map <- ggplot(map_df, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes_string(fill = fill_var), colour = 'white') +
  scale_fill_viridis_c(option = "C", direction = -1,na.value="grey") +
  labs(fill = leg_label) +
  {if(Switch)ggtitle(paste0(title, " Map ", dt))} +
  geom_text_repel(data = map_lab_data, aes(label = location), max.overlaps = 2,
            size=3.5, min.segment.length = 2, colour = 'black',
            segment.alpha = 0, segment.color = 'grey50') +
  theme_map() +
  coord_cartesian(ylim = c(-50, 90)) +
  theme(    axis.title=element_blank(),
            axis.text=element_blank(),
            axis.ticks=element_blank(),
            plot.title = element_text(hjust = 0.6, size = 14,face = "bold"),
            legend.text=element_text(size=10,family="serif"),
            legend.title=element_text(size=10,family="serif"),
            legend.position="right",
            legend.direction = "vertical")
   
  return(map)
}
```


# **World Countries - 2021-12-30**

### Maps
```{r,echo=FALSE, message=FALSE, warning=FALSE}
ggarrange(
country_map(df_world_20211230,'2021-12-30',"stringency","World",'no',"Stringency"),
country_map(df_world_20211230,'2021-12-30',"sub_stringency","World",'no',"Sub\nStringency"),
country_map(df_world_20211230,'2021-12-30',"lockdowns_cubed","World",'no',"Lockdowns\nCubed"), 
country_map(df_world_20211230,'2021-12-30',"total_deaths_per_million","World",'no',"Total Deaths\n/Million"), nrow = 2, ncol = 2) %>% annotate_figure(top = text_grob(paste0("World Map ", "2021-12-30"), color = "black", 
          face = "bold", size = 14))

country_map(df_world_20211230,'2021-12-30',"stringency","World",'yes',"Stringency")
country_map(df_world_20211230,'2021-12-30',"sub_stringency_cubed","World",'yes',"Sub\nStringency^3")
country_map(df_world_20211230,'2021-12-30',"lockdowns","World",'yes',"Lockdowns")
```

### Correlations
```{r,echo=FALSE, message=FALSE, warning=FALSE}
corr_table(df_world_20211230)
#corr_plot(df_world_20211230)
corr_matrix(df_world_20211230)
```

### Scatter plots - total covid deaths per million vs. stringency / sub_stringency cubed
```{r,echo=FALSE, message=FALSE, warning=FALSE}
ggarrange(
 country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","stringency", "Stringency",'no','no') + rremove("ylab"),
 country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","lockdowns_cubed", "lockdowns^3",'no','no') + rremove("ylab"),
 country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","median_age","Median Age",'no','no') + rremove("ylab"),
 country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","people_fully_vaccinated_per_hundred","Fully Vaccinated %",'no','no') + rremove("ylab"), ncol = 2,nrow=2, common.legend = T, legend = c("right")) %>% 
  annotate_figure(map, left = text_grob("Total Deaths per Million", rot = 90, vjust = 1))

country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","stringency", "Stringency",'no','no',"fac")
country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","lockdowns", "lockdowns",'yes','no',"fac")
country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","median_age","Median Age",'no','no',"fac")
country_scatter(df_world_20211230,"total_deaths_per_million","Total Deaths per Million","people_fully_vaccinated_per_hundred","Fully Vaccinated %",'no','no',"fac")
```

### Regression
```{r,echo=FALSE, message=FALSE, warning=FALSE}
mlr_print(create_model_full(df_world_20211230))
mlr_vif(create_model_full(df_world_20211230))

mlr_print(create_model_full_2(df_world_20211230))
mlr_vif(create_model_full_2(df_world_20211230))

mlr_print(create_model_full_3(df_world_20211230))
mlr_vif(create_model_full_3(df_world_20211230))

mlr_print(create_model_full_4(df_world_20211230))
mlr_vif(create_model_full_4(df_world_20211230))
avPlots(create_model_full_4(df_world_20211230))

mlr_print(create_model_stringency(df_world_20211230))
mlr_vif(create_model_stringency(df_world_20211230))
avPlots(create_model_stringency(df_world_20211230))

mlr_print(create_model_sub_stringency(df_world_20211230))
mlr_vif(create_model_sub_stringency(df_world_20211230))
avPlots(create_model_sub_stringency(df_world_20211230))

mlr_print(create_model_sub_stringency_cubed(df_world_20211230))
mlr_vif(create_model_sub_stringency_cubed(df_world_20211230))
avPlots(create_model_sub_stringency_cubed(df_world_20211230))

mlr_print(create_model_lockdowns(df_world_20211230))
mlr_vif(create_model_lockdowns(df_world_20211230))
avPlots(create_model_lockdowns(df_world_20211230))

mlr_print(create_model_lockdowns_cubed(df_world_20211230))
mlr_vif(create_model_lockdowns_cubed(df_world_20211230))
avPlots(create_model_lockdowns_cubed(df_world_20211230))
```


#### Countries in the analysis
```{r,echo=FALSE, message=FALSE, warning=FALSE}
# List of countries in analysis
df_world_20211230 %>% select(location) %>% 
  kbl(caption = paste0("Countries in analysis (n = ", length(df_world_20211230 %>% select(location) %>% pull()),")")) %>% 
  kable_classic(full_width = F) 
# Number of countries in analysis 
```


### Data sources:
* [Our World in Data](https://covid.ourworldindata.org/data/owid-covid-data.csv)
* [The Oxford COVID-19 Government Response Tracker](https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv)
* [Average latitude & longitude for Countries](https://raw.githubusercontent.com/albertyw/avenews/master/old/data/average-latitude-longitude-countries.csv)
* [Obesity Data](https://github.com/camminady/overweight)

```{r,echo=FALSE, message=FALSE, warning=FALSE}
#rm(list=setdiff(ls()," "))
```

