---
title: "Covid Data and Restrictions - Regression Models"
output: github_document
---
```{r setup, echo=FALSE, message=FALSE, warning=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```


Load required packages
```{r}
if (!require(pacman)) install.packages('pacman')
library(pacman)
p_load(tidyverse,ggpubr, map_data,ggrepel,ggtext,scales,viridis,ggthemes)
options(scipen=999)
options(warn=-1)
```

Import data frames saved from Extraction.RMD
```{r}
lally_countries <- c("Austria","Albania","Belgium","Bosnia and Herzegovina","Bulgaria","Croatia","Cyprus","Czechia","Denmark","Estonia","Finland","France","Germany","Greece","Hungary","Iceland","Ireland","Italy","Latvia","Lithuania","Luxembourg","Netherlands","Norway","Poland","Portugal","Romania","Serbia","Slovakia","Slovenia","Spain","Sweden","Switzerland","United Kingdom")


df_europe_20201230 <- readRDS("OxOw_Extraction_europe_20201230_small.rds") %>% filter(location %in% lally_countries)
 
df_europe_20211230 <- readRDS("OxOw_Extraction_europe_20211230_small.rds") %>% filter(location %in% lally_countries)

```

Copy regression analysis from [Lally (2022)](https://link.springer.com/content/pdf/10.1007/s40592-021-00148-y.pdf) paper. 
```{r}
lally_max_si <- lm(formula = total_deaths_per_million ~ max_stringency + population_density +
              date_first_death_days, data = df_europe_20201230)
summary(lally_max_si)

lally_res <- lm(formula = total_deaths_per_million ~ total_restrictions + population_density + date_first_death_days, df_europe_20201230)
summary(lally_res)

ss_max_si <- lm(formula = total_deaths_per_million ~ max_stringency + population_density +
              date_first_death_days, data = df_europe_20211230)
summary(ss_max_si)

ss_res <- lm(formula = total_deaths_per_million ~ total_restrictions + population_density +
              date_first_death_days, data = df_europe_20211230)
summary(ss_res)

```
